### ISSUE TITLE
[Idea / Feature request]

### ISSUE THREAD

**Issue by nmateo** [hinto-janai/gupax#1]
Could it be possible that in the Xmrig part of Gupax, we could monitor / control multiple xmrig miners with ssh, could be really usefull, thanks ;)

**Comment by hinto-janaiyo** [comment]
I'm not sure what the UI would be, a full Powershell/Bash shell? Or a HTTP (over SSH) client sending calls to XMRig's HTTP API? I think at that point using a regular terminal would be better but I'll think about it.
