### ISSUE TITLE
only 1 character is allowed in sudo password field of xmrig tab

### ISSUE THREAD

**Issue by sonhng97** [hinto-janai/gupax#103]
## OS & Version:
Nobara 6.11.3-200.fsync.fc40.x86_64
Gupax v1.3.9

## Bug
Can only enter 1 character in the sudo password field, no messages from console.
I have tried restarting, boot with different kernel (6.11.4) without avail.

**Comment by hinto-janai** [comment]
Are you using Wayland? Does the latest release still have this problem? https://github.com/hinto-janai/gupax/releases/latest.

**Comment by sonhng97** [comment]
I no longer have this problem. Yes I'm using wayland. It seems like the problem only occured in Gnome though. On hyprland and plasma I do not have this problem.
