### ISSUE TITLE
Add optional MQTT reporting of stats 

### ISSUE THREAD

**Issue by ChavoDeLa** [hinto-janai/gupax#104]
include mosquitto-MQTT backend with Linux and/or Windows bundles

provide input option for MQTT host info, UN/PW on GUPAX tab, along with tick box to "publish stats to MQTT"

Add additional lines to the code which publishes data to 'STATUS' tab currently, to mirror data to an MQTT server.

example:  mosquitto_pub -t "PCIDexample/gupax/XMRIG" -m "hashrate: 6724 H/s"

publish to a unique topic per install, in case multiple gupax installs are published to the same server in a farm.

/PCuniqueID/gupax/P2P/etc**
/PCuniqueID/gupax/XMRIG/etc**
/PCuniqueID/gupax/GUPAX/etc**

this will allow monitoring integration with local and outbound servers without requiring access to headless machines....it would open a ton of doors integration-wise for little effort.

thanks!

**Comment by hinto-janai** [comment]
XMRig and P2Pool both have public APIs, using these would be better than Gupax for headless servers.
