### ISSUE TITLE
update XMRIG to include XMRIG merged pull #3569

### ISSUE THREAD

**Issue by ChavoDeLa** [hinto-janai/gupax#105]
## OS & Version:
Linux 24.10

## Bug
JSON output at 0.0.0.0:18088/1/summary is truncated for some time after starting XMRIG

## Steps
1. go to LANIP:18088/1/summary from any web browser where LANIP is the IP of any active XMRIG HTTP API server running in GUPAX 1.3.9, having been started within 10 min , see truncated JSON output.  cannot be monitored from XMRIG workers until hashrates are populated at length.

issue is fixed with XMRIG merged pull request #3569 as of last week

thanks

**Comment by hinto-janai** [comment]
Should be fixed with [v1.3.10](https://github.com/hinto-janai/gupax/releases/tag/v1.3.10) or an updated XMRig.
