### ISSUE TITLE
Won't open on MacOS (both standalone and bundle). Source build works

### ISSUE THREAD

**Issue by AlexeyBukin** [hinto-janai/gupax#107]
## OS & Version:
MacOs 14.6.1, Gupax v1.3.9

## Bug
Won't open on MacOS (system tells something about corrupted application)

## Steps
1. Download package from the official website
2. Open the package
3. Be disappointed

## Screenshots
<img width="295" alt="Снимок экрана 2024-10-31 в 23 30 16" src="https://github.com/user-attachments/assets/2fa944b4-c5e8-4b5c-8c6e-618488972e26">

**Comment by hinto-janai** [comment]
Can you try the latest release?: https://github.com/hinto-janai/gupax/releases/latest

**Comment by AlexeyBukin** [comment]
> Can you try the latest release?: https://github.com/hinto-janai/gupax/releases/latest

Same error :-(

**Comment by AlexeyBukin** [comment]
Duplicate of https://github.com/hinto-janai/gupax/issues/51

**Comment by hinto-janai** [comment]
Does `xattr` fix the issue?
