### ISSUE TITLE
✨ Feature Request - Hide unused processes from `Status` tab

### ISSUE THREAD

**Issue by Rikj000** [hinto-janai/gupax#108]
**Feature request**
It would be nice if only used processes would be displayed on the `Status` tab.

Hiding could be triggered by either or both:
- Clearing the `P2Pool/XMRig PATHs`
- Not starting the respective process

**Additional context**
In all honesty, in [`Gupax`](https://github.com/hinto-janai/gupax) this never really bothered me much,   
however [`Gupaxx`](https://github.com/Cyrix126/gupaxx) added a lot of processes (Monero Node, XMRig-Proxy and XvB),   
and I will likely not be using them all, so ability to hide some would make the UI in the `Status` tab a lot cleaner.

Still I also felt like it could be a useful enhancement for upstream.   
Tagging @Cyrix126 since he might be interested in this issue as well.

**Comment by Cyrix126** [comment]
Noted in [IDEAS](https://github.com/Cyrix126/gupaxx/blob/main/IDEAS.md#allow-to-hide-status-column).

**Comment by hinto-janai** [comment]
I think the greyed out box/text is a good indication that the process is turned off. This may be better in Gupaxx where there are more processes.

**Comment by Cyrix126** [comment]
@Rikj000 it is implemented in https://github.com/Cyrix126/gupaxx/releases/tag/v1.7.0

**Comment by Rikj000** [comment]
Awesome, many thanks @Cyrix126!  I've just tested it and it works nicely! :tada: 

If you're open for it, here's some feedback for possible further UI enhancements:
1. Move `Visible columns:` to `Gupax(x)` tab, since they're settings,   
which do not really belong under the status tab, perhaps also rename `columns` to `processes`, see 2.
2. Hide the buttons from the top if visible columns are disabled, since they're kinda useless if the process is not used.
3. Stretch the status columns to fit the screen, but keep a minimal width to retain readability.

![Gupaxx-Hide-unused-processes-enhancements](https://github.com/user-attachments/assets/76be1695-2d45-43b8-a2cd-ec59cfe560a1)

No matter if you decide to implement these, I'm already very thankful for the work done! :pray:

**Comment by Cyrix126** [comment]
I invite you to create an issue on gupaxx repo to discuss it.
