### ISSUE TITLE
RandomX Benchmark Feature Request

### ISSUE THREAD

**Issue by ACK-J** [hinto-janai/gupax#12]
Within the GuPax "Status" tab there is a section that identifies the user's processor and clock speed. I think it would be cool to either download or query the [Xmrig benchmark site](https://xmrig.com/benchmark) to display the expected hashrate for the cpu. 

![image](https://user-images.githubusercontent.com/60232273/211647852-9c7d9a8b-5304-435d-afcc-b028d32976a3.png)

**Comment by hinto-janai** [comment]
This was implemented in [`v1.2.0`](https://github.com/hinto-janai/gupax/releases/tag/v1.2.0), thank you for the idea.
