### ISSUE TITLE
Consider using pkexec for xmrig's elevated permissions

### ISSUE THREAD

**Issue by busyboredom** [hinto-janai/gupax#17]
Hey, have you considered pkexec for handling xmrig's permission requirement? 

I was working on a project very similar to yours a while ago before I knew Gupax was in progress, and pkexec is what I used for the xmrig permission issue. Like this https://github.com/busyboredom/ministo/blob/main/src-tauri/src/xmrig.rs#L77

Feel free to close this issue if you've already decided against it, I won't be offended.

**Comment by hinto-janaiyo** [comment]
`sudo` is Unix, `pkexec` is Linux (and desktop) specific.

The real problem is Windows permissions.
