### ISSUE TITLE
2 machines of diff OS with the same wallet set up - only one miners connected shown

### ISSUE THREAD

**Issue by mobilelifeful** [hinto-janai/gupax#18]
one machines is window， and the other is mac, and both machines are connected with the same p2pool and the same wallet. 
but only one miner connected shown, is that normnal ?

**Comment by hinto-janai** [comment]
Are both machines XMRig's connected to _one_ machines P2Pool?

**Comment by mobilelifeful** [comment]
> Can you show some screenshots of P2Pool/XMRig tabs? Maybe censor your wallet.

win 
<a href="https://imgbb.com/"><img src="https://i.ibb.co/Sd0CfDM/win.png" alt="win" border="0"></a>

mac
<a href="https://ibb.co/RBbSGTt"><img src="https://i.ibb.co/xfLsKqw/mac.png" alt="mac" border="0"></a>

**Comment by hinto-janai** [comment]
You're running 2 P2Pools. You only need 1.

Turn off the macOS `P2Pool` and [connect macOS `XMRig`](https://github.com/hinto-janai/gupax#XMRig-1) to the Windows `P2Pool`.

**Comment by mobilelifeful** [comment]
> You're running 2 P2Pools. You only need 1.
> 
> Turn off the macOS `P2Pool` and [connect macOS `XMRig`](https://github.com/hinto-janai/gupax#XMRig-1) to the Windows `P2Pool`.

My desktop computer sits at home, at the same time  gaming laptop to mine while not home.  any suggestion ? Thank you again.

**Comment by hinto-janai** [comment]
You can open P2Pool port [`3333`](https://github.com/SChernykh/p2pool#windows) on desktop and connect to it with your laptop's Gupax/XMRig:
```
Name: Desktop P2Pool
IP:   xx.xx.xx.xx (your desktop's ip)
Port: 3333
Rig:  Laptop
```

It might be better to just run `P2Pool + XMRig` on your laptop.
