### ISSUE TITLE
no auto update . no update manual

### ISSUE THREAD

**Issue by trucoteca2** [hinto-janai/gupax#20]
Autoupdate doesn't do well. I do the autoupdate from gupax and it is downloaded, version 1.2.1, I have version 1.2.0 running.

Even if I restart GUPAX or the machine, it's still at 1.2.0. I've hand-downloaded 1.2.1 and copied the files to the working folder, and when I launch gupax it's still 1.2.0

I don't know what else I can do, I think there is a problem in the update

**Comment by trucoteca2** [comment]
Windows 10, gupax bundle

**Comment by hinto-janai** [comment]
Thank you for notifying.

You're right, the Windows zips came with `v1.2.0` instead of `v1.2.1`.

I've fixed the release, can you try updating again?

**Comment by trucoteca2** [comment]
Now yes, I was going crazy, I thought I was clumsy. Thanks for the quick solution. First time now from gupax's own autoupdate service
