### ISSUE TITLE
Reword Xmrig info text

### ISSUE THREAD

**Issue by CryptoGrampy** [hinto-janai/gupax#30]
I thought the info text for the address was slightly unclear on the Xmrig tab for newbies.  Creating this issue to make it a little more clear.  Does this address do anything if you already have an address in the P2Pool tab?

https://github.com/hinto-janai/gupax/blob/8fbd949342d0fb5ffaa4a128bf622501ca7daecf/src/constants.rs#L344

Old: 
Specify which Monero address to payout to. This does nothing if mining to P2Pool since the address being payed out to will be the one P2Pool started with. This doubles as a rig identifier for P2Pool and some pools.

New:
If you're not using P2Pool, add your Monero payout address here. This address is also used as the identifier of your rig on some pools.

**Comment by hinto-janai** [comment]
Sure, open a PR with the change.
