### ISSUE TITLE
Use polkit's `pkexec` instead of asking for the root password directly

### ISSUE THREAD

**Issue by KodiCraft** [hinto-janai/gupax#31]
**Feature request**
On Linux, Gupax has its own little UI that requests the admin password in order to launch XMRig. This is good reason for someone not to trust it, especially knowing what kind of issues have plagued cryptocurrency in the past. Polkit is installed by default on many Linux distributions and `pkexec` requests the user's password through an agent the user already trusts. This would greatly help transparency, trust, and would plug in better with the way that Linux systems tend to handle permissions.

**Comment by hinto-janai** [comment]
> pkexec requests the user's password through an agent the user already trusts

Gupax receiving elevated permissions, whether through `sudo` or `pkexec` both result in Gupax having access to elevated permissions, so it doesn't matter, you have to "trust" Gupax with root permissions in both situations.

See https://github.com/hinto-janai/gupax/issues/17 and https://github.com/hinto-janai/gupax/issues/19.
