### ISSUE TITLE
How to use OpenCL within GUPAX

### ISSUE THREAD

**Issue by Lancaban** [hinto-janai/gupax#35]
This is less of a feature request and more of a help request, but wasn't sure where else to ask for support.

I previously set up XMRig to mine using my AMD video cards, openCL on Linux. I am very new to this, and although I got it working successfully, my understanding of the command line options isn't great.

I got interested in GUPAX when I learned about P2Pool mining and saw it as a way to simplify my entire setup/process.

That said, as far as I can tell, the Default XMRig settings in GUPAX don't include an option to use openCL.

I know I have the backends (openCL etc. etc.) installed properly as I was using them without error before.

In GUPAX I know I can override the default settings with my own,  --opencl is all it would take, but I would then have to replicate the rest of the default settings string that GUPAX normally uses, and that's where I get tripped up.

I am using a Local Monero Node, configured through the Monero GUI.
XMRig in GUPAX is set to use Local P2Pool, all the standard settings, like out of the box just work as they are, everything runs fine.

But if I wanted to add the --openCL flag, how would I format the rest of the settings string, to replicate the defaults GUPAX is using? (short of begging to have a checkbox to use OpenCL, get added to the program).

I realize it's probably a fairly niche request, but any help would be great.

**Comment by hinto-janai** [comment]
The GPU-related options in XMRig are from a bygone period where Monero was able to be efficiently mined with them. This hasn't been the case since RandomX was launched on mainnet (2019).

My advice would be to not mine Monero with your GPU at all, and instead mine something else that has GPU support, your electricity will be much better spent.

With that said, if you still want to mine Monero with a GPU:

Here are the current default arguments Gupax starts XMRig with:
```bash
--user YOUR_WALLET --threads YOUR_THREADS --rig-id Gupax_v1_2_2 --url 127.0.0.1:3333 --http-host 127.0.0.1 --http-port 18088 --no-color
```

To see which GUI settings map to which flags, start Gupax in a terminal and launch XMRig. Gupax will log the arguments used, which you can then use in Gupax.

You could also just specify:
```bash
--config "/path/to/your/xmrig_config.json"
```
and XMRig will use that.

**Comment by Lancaban** [comment]
Good to know, thanks for the advice!!  Mining "efficiently" is not really my goal,  when I did Xmri I initially went from about a 10K hash rate to 16K-ish by enabling OpenCL which is why I was curious

Electricity is not a personal concern, my PC stays on 24/7, and I have one of the lowest usage rates in the US (about 3 cents per killowat hour) I usually barely break $40/mo. I was just looking for ways to makes use of the spare CPU cycles, and with BOINC being... well, mostly dead, and seeing that Mullvad accepts Monero I figured I'd give it a shot.

That said Waste-not want not and all that, I'll probably leave it off, I appreciate you helping me learn about it more, and pointing me in the right direction.

**Comment by mubali1987** [comment]
How to activate opencl?

**Comment by Lancaban** [comment]
@mubali1987 
as stated above, mining Monero with OpenCL just isn't really a thing anymore. 

I've been mining with just my CPU steadily since making my previous post. It stays at a pretty good clip, and the currency itself is fairly stable. I got involved for the privacy aspects, not to get rich.  

Mining with just a CPU does a pretty good job, but Monero is a fairly stable crypto, it's not the one to use if you are looking to get rich. I mine to help the network, and because it makes me feel good to support a project I believe in.

If you want to use/support Monero, Gupax is probably the easiest/best way to do it.  Dpon't worry about OpenCL, just use CPU and you'll be fine.

If you want to Mine Crypto for profit, you might want to look at a different currency.

**Comment by mubali1987** [comment]
thx
