### ISSUE TITLE
[Feature] give macos arm64 a arm64 xmrig

### ISSUE THREAD

**Issue by anyuzu99** [hinto-janai/gupax#36]
**Feature request**
https://github.com/xmrig/xmrig/releases/download/v6.19.2/xmrig-6.19.2-macos-arm64.tar.gz

**Additional context**
i move the file manually to gupax.app, and it works.

**Comment by hinto-janai** [comment]
Next release will have a full `macos-arm64` Gupax/P2Pool/XMRig.

**Comment by hinto-janai** [comment]
https://github.com/hinto-janai/gupax/releases/tag/v1.2.3

**Comment by anyuzu99** [comment]
<img width="611" alt="Screenshot 2023-06-04 at 07 43 29" src="https://github.com/hinto-janai/gupax/assets/16492117/7bb926d3-9234-4e33-a444-55e5df303cf0">

can not use

**Comment by hinto-janai** [comment]
You may have to "trust" Gupax.

1. System Preferences
2. Security & Privacy
3. "Open Anyway"

![mac](https://github.com/hinto-janai/gupax/assets/101352116/dbd73a0b-5e98-4c6e-b341-b1685cd8b22b)

**Comment by anyuzu99** [comment]
there is no such button
![Screenshot 2023-06-04 at 09 47 46](https://github.com/hinto-janai/gupax/assets/16492117/1595a3a9-ac45-4dd3-83c2-88512a687ed2)

**Comment by hinto-janai** [comment]
Can you run:
```bash
./Gupax.app/Contents/MacOS/gupax
```
in a terminal and show the output?

**Comment by anyuzu99** [comment]
![Screenshot 2023-06-04 at 12 19 57](https://github.com/hinto-janai/gupax/assets/16492117/d5c17f82-3745-4fbc-834f-da69bf5cadd8)
![Screenshot 2023-06-04 at 12 20 09](https://github.com/hinto-janai/gupax/assets/16492117/0bfa7d6a-0502-47a9-90ac-ee694be5450c)

**Comment by hinto-janai** [comment]
I've updated the release, can you try again?

https://github.com/hinto-janai/gupax/releases/download/v1.2.3/gupax-v1.2.3-macos-arm64-standalone.tar.gz

**Comment by anyuzu99** [comment]
￼
The same

**Comment by hinto-janai** [comment]
Can you try this?

[gupax-v1.2.3-macos-arm64-standalone.tar.gz](https://github.com/hinto-janai/gupax/files/11646237/gupax-v1.2.3-macos-arm64-standalone.tar.gz)

**Comment by anyuzu99** [comment]
￼
Btw, the windows latest version also couldn’t start.

**Comment by anyuzu99** [comment]
app finally start after this command `xattr -d com.apple.quarantine /Applications/Gupax.app`
