### ISSUE TITLE
P2Pool/XMRig backup node/pool

### ISSUE THREAD

**Issue by hinto-janai** [hinto-janai/gupax#38]
Both `[P2Pool]` & `[XMRig]` tabs have UI for adding/deleting nodes/pools via a list.

There should also UI for allowing fallback, so when a node/pool goes down, the other ones set in the list are used as backup.

XMRig allows this natively, so just passing the extra pools via the startup arguments is sufficient.

P2Pool does not (yet), although since Gupax parses P2Pool output anyway, we could implement a bad hack:
- detect node connection issues
- restart P2Pool with a different node argument

**Comment by SChernykh** [comment]
@hinto-janai P2Pool can now support multiple nodes in the command line: https://github.com/SChernykh/p2pool/blob/master/docs/COMMAND_LINE.MD#multiple-backup-hosts
It will be able to switch to another node without restart.

**Comment by hinto-janai** [comment]
Added in [`v1.3.0`](https://github.com/hinto-janai/gupax/releases/tag/v1.3.0).
