### ISSUE TITLE
MacOS coud not start

### ISSUE THREAD

**Issue by Hausmeisterle** [hinto-janai/gupax#39]
After Update > it´wan´t start anymore on MaOS .

Nothing changed .

Error : GUPAX xcoud dort start - without any additional Info

**Comment by hinto-janai** [comment]
Thanks for the report, I've updated the release, can you try again?

**Comment by Hausmeisterle** [comment]
Hi,

Now it’s working again :-)


I have a other question, please how can I add commands to xmrig ?
On console I have added —wrmsr=17 , and other commands so I get better hash rate.

But how to add in GUPAX ?


Thank you

Regards

**Comment by hinto-janai** [comment]
Gupax runs XMRig as sudo which should automatically enable MSR mods. You don't need to add any commands.
