### ISSUE TITLE
v1.3.0 Updates disabled on Windows

### ISSUE THREAD

**Issue by shaneo88** [hinto-janai/gupax#40]
**Describe the bug**
I have just updated to Gupax v1.3.0. When opening it says Updates Disabled. This Gupax was built as a Linux distro and updates via tor and auto updates are disabled, or something to that effect.

**To Reproduce**
1. Download the Windows Gupax v1.3.0 build from www.gupax.io
2. Alternatively, let Gupax Auto Update to v1.3.0
3. Open Gupax and see that Updates Disabled message

**Screenshots**
https://i.imgur.com/4Rh0Oz5.png

**OS & Version:**
e.g: Windows 11 Pro Insider 25905, Gupax v1.3.0

**Comment by hinto-janai** [comment]
Should be fixed in [`v1.3.1`](https://github.com/hinto-janai/gupax/releases/tag/v1.3.1), can you try again?

**Comment by shaneo88** [comment]
Fixed. Thanks for the quick fix
