### ISSUE TITLE
Status Page showing ??? values for fields

### ISSUE THREAD

**Issue by Burner8** [hinto-janai/gupax#46]
**Describe the bug**
What is the bug?

**To Reproduce**
1. Go to 'Status Page' while P2Pool and XMRig processes are Green/running.
2. See it.  Believe it.  Possibly accept it?  Noh.  Noh-noh-noh.
3. See error

Now, full disclosure:  I run UFW (Uncomplicated FireWall) and wonder if something is blocking the http API, but I'm a noob in that field as well ^_^

Also worth mentioning: the XMRig tab accepts the [h] command and shows the hashrate. So as far as I can tell, the system is indeed mining, just not being reflected on the Status page. Uninstalled Gupax 1.3.1 and restarted the configuration, sadly it reappears on my second install.

**Screenshots**
![1b_Gupax_Status_Error](https://github.com/hinto-janai/gupax/assets/141272582/6bd3ff1d-dd0b-458f-8044-d70fbca435e4)

**OS & Version:**
Debian 12 LTS (fresh install, fully updated) + Gupax 1.3.1

**Comment by Burner8** [comment]
Also worth mentioning:  the XMRig tab accepts the [h] command and shows the hashrate.  So as far as I can tell, the system is indeed mining, just not being reflected on the Status page.  Uninstalled Gupax 1.3.1 and restarted the configuration, sadly it reappears on my second install.

**Comment by hinto-janai** [comment]
Can you try opening http://localhost:18088/1/summary in a browser while XMRig is running? (Replace 18088 if you set a custom port)

If it does not open, it may be a problem with your system. If it does, it's probably a problem in Gupax.

**Comment by Burner8** [comment]
So, I have the following ports on the XMRig tab:
HTTP API Port:  18088

The following on the P2Pool tab:
RPC:  18081
ZMQ:  18083

When I have XMRig running (hashrate is low 13000 with the [h] command)  the link you provided doesn't load in the browser.  I don't know if I need to replace port 18088 with one from the P2Pool tabs.  Fun fact:  in the US, 18088 is the zip code of my last house in Pennsylvania, US before I moved overseas to Europe.  It's been a long time since I've seen it, so I'm amused.
