### ISSUE TITLE
bug: windows auto update

### ISSUE THREAD

**Issue by wolfderechter** [hinto-janai/gupax#47]
**Describe the bug**
The auto-update on windows has never worked for me.  I've tried on multiple versions.

**To Reproduce**
1. Be on windows
2. Go to the gupax tab
3. Click on 'Check for updates'
4. 'update failed | metadata fetch failed'

**Screenshots**
![image](https://github.com/hinto-janai/gupax/assets/60930264/a5d2b071-e4ab-4cda-b2e7-fb09075e841c)

**OS & Version:**
Windows 10, Gupax v1.3.1

**Comment by hinto-janai** [comment]
I cannot reproduce, can you try with Tor disabled?

**Comment by wolfderechter** [comment]
> I cannot reproduce, can you try with Tor disabled?

Aha that works
