### ISSUE TITLE
Status page Issue

### ISSUE THREAD

**Issue by Ranchdad86** [hinto-janai/gupax#48]
Status page is blank. with 0s and ??s

P2Pool and XMRIG running

Instructions from readme for setting up a local node were followed. Everything is running and mining fine from this computer.

Multiple other systems on my network are also mining fine from same local node

**Screenshots**
Attached
![Screenshot 2023-08-29 013847](https://github.com/hinto-janai/gupax/assets/142755220/5d090374-a88e-4747-851f-e87983eef9e9)

**OS & Version:**

Windows 11, version 1.3.1

**Comment by hinto-janai** [comment]
Can you check inside the P2Pool folder?

It should have 3 folders called `local`, `network` and `pool`.

Inside each folder there should be some files containing some JSON data.

If these files/folders don't exist something is wrong.

**Comment by Ranchdad86** [comment]
All 3 folders exist. The pool folder has a file called "blocks" the local folder has a file called "stratum" the network folder is empty

**Comment by hinto-janai** [comment]
Yes it's normal, `monerod` says "not mining" because the built-in miner isn't mining.

Payout time varies. [You need a share while P2Pool finds a block](https://github.com/SChernykh/p2pool#how-payouts-work-in-p2pool), so it depends on your luck on finding a share and P2Pool's  luck finding a Monero mainchain block. You can use https://p2pool.observer to see more stats.

Does the `stratum` file contain data? It should look something like:
```json
{"hashrate_15m":13067,"hashrate_1h":13197,"hashrate_24h":13926,"total_hashes":11964874,"shares_found":13,"shares_failed":0,"average_effort":153.622,"current_effort":231.512,"connections":1,"incoming_connections":1,"block_reward_share_percent":0.154}
```

**Comment by Ranchdad86** [comment]
> Yes it's normal, `monerod` says "not mining" because the built-in miner isn't mining.
> 
> Payout time varies. [You need a share while P2Pool finds a block](https://github.com/SChernykh/p2pool#how-payouts-work-in-p2pool), so it depends on your luck on finding a share and P2Pool's luck finding a Monero mainchain block. You can use https://p2pool.observer to see more stats.
> 
> Does the `stratum` file contain data? It should look something like:
> 
> ```json
> {"hashrate_15m":13067,"hashrate_1h":13197,"hashrate_24h":13926,"total_hashes":11964874,"shares_found":13,"shares_failed":0,"average_effort":153.622,"current_effort":231.512,"connections":1,"incoming_connections":1,"block_reward_share_percent":0.154}
> ```

The pool has found blocks. I'm running about 200 kh/s and run 24/7. Getting a share has never been an issue. 

The stratum file contains all of that data but all of the values are zero. I know that is not correct. I've been checking status directly in monerod and it is consistently 64/32 sometimes 64/31. I'm on a gigabit internet connection. I'm going to try to run p2 pool directly and just use xmrig directly to point for 24hours to see If the issue is coming from something with them or is an issue with gupax

**Comment by Ranchdad86** [comment]
> > Yes it's normal, `monerod` says "not mining" because the built-in miner isn't mining.
> > Payout time varies. [You need a share while P2Pool finds a block](https://github.com/SChernykh/p2pool#how-payouts-work-in-p2pool), so it depends on your luck on finding a share and P2Pool's luck finding a Monero mainchain block. You can use https://p2pool.observer to see more stats.
> > Does the `stratum` file contain data? It should look something like:
> > ```json
> > {"hashrate_15m":13067,"hashrate_1h":13197,"hashrate_24h":13926,"total_hashes":11964874,"shares_found":13,"shares_failed":0,"average_effort":153.622,"current_effort":231.512,"connections":1,"incoming_connections":1,"block_reward_share_percent":0.154}
> > ```
> 
> The pool has found blocks. I'm running about 200 kh/s and run 24/7. Getting a share has never been an issue.
> 
> The stratum file contains all of that data but all of the values are zero. I know that is not correct. I've been checking status directly in monerod and it is consistently 64/32 sometimes 64/31. I'm on a gigabit internet connection. I'm going to try to run p2 pool directly and just use xmrig directly to point for 24hours to see If the issue is coming from something with them or is an issue with gupax

So After 24 hours running on straight p2pool and XMRIG with no gupax the difference is night and day...within 2 hours of switching, found a share. Found multiple within 24 hours which is what is normal when I was mining directly from the wallet previously with multiple payouts as normal....this is vs 72 hours on GUPAX with no shares found, which is incredibly abnormal. 

I changed nothing on any of my secondary systems on the network. They are all still using xmrig to point to the main system. 

The same exact settings were used in p2pool and xmrig as were used in gupax. Nothing changed on monerod. The only thing changed was using it direct vs gupax.

Concerned where this bug would come from and what in gupax isn't working right?
