### ISSUE TITLE
checksums not correct

### ISSUE THREAD

**Issue by programmerOne** [hinto-janai/gupax#49]
I've downloaded the v1.3.1 windows x64, both the bundled and the standalone archives from the official website and the checksums are coming back incorrect.  They don't match whats displayed on the site.  This is as of 8/3/2023 and 8/4/2023.

Its possible im doing it wrong but I don't think so.  I've tried multiple different ways .

**Comment by hinto-janai** [comment]
I cannot reproduce, what command are you using?
```bash
> sha256sum -c SHA256SUMS
gupax-v1.3.1-linux-x64-bundle.tar.gz: OK
gupax-v1.3.1-linux-x64-standalone.tar.gz: OK
gupax-v1.3.1-macos-arm64-bundle.tar.gz: OK
gupax-v1.3.1-macos-arm64-standalone.tar.gz: OK
gupax-v1.3.1-macos-x64-bundle.tar.gz: OK
gupax-v1.3.1-macos-x64-standalone.tar.gz: OK
gupax-v1.3.1-windows-x64-bundle.zip: OK
gupax-v1.3.1-windows-x64-standalone.zip: OK
sha256sum: WARNING: 8 lines are improperly formatted

> gpg --verify SHA256SUMS 
gpg: Signature made Wed 19 Jul 2023 06:48:25 PM UTC
gpg:                using EDDSA key 31C5145AAFA5A8DF1C1DB2A6D47CE05FA175A499
gpg: Good signature from "hinto.janai <hinto.janai@protonmail.com>" [ultimate]
```

**Comment by programmerOne** [comment]
omg im so sorry, i was being an idiot.  For some reason i was doing SHA-1 instead of 256, i was trying to do it between tasks and i made an idiotic mistake thinking the SHA1 hash was what i wanted, which of course wasnt matching lol. Sorry to waste your time for such a stupid mistake!
