### ISSUE TITLE
Cannot start ARM M1 binary package (but build it ok)

### ISSUE THREAD

**Issue by kwccoin** [hinto-janai/gupax#51]
**Describe the bug**
cannot start the ARM M1 (Intel is ok)

**To Reproduce**
1. Download
2. Click on App
3. See error of damaged App 

**Screenshots**
<img width="251" alt="Screenshot 2023-09-14 at 10 50 46 AM" src="https://github.com/hinto-janai/gupax/assets/7194447/24565ab2-c99f-4af6-8aa0-81c289861a0f">

**OS & Version:**
macOS 13.5.2

I finally built one myself and hence I resolve the issue.  I am not sure others want to do this as well.

**Comment by kwccoin** [comment]
Probably not related but I tried to install it by cloning the GitHub and build from source.  Cloning via Github Desktop produce this error:

```
remote: Enumerating objects: 7, done.        
remote: Counting objects: 100% (7/7), done.        
remote: Compressing objects: 100% (1/1), done.        
remote: Total 4 (delta 3), reused 3 (delta 3), pack-reused 0        
From https://github.com/hinto-janai/gupax
 * [new branch]      main       -> upstream/main
 * [new branch]      tray       -> upstream/tray
 * [new tag]         v0.0.1     -> v0.0.1
 * [new tag]         v0.1.0     -> v0.1.0
 * [new tag]         v0.5.0     -> v0.5.0
 * [new tag]         v0.9.0     -> v0.9.0
 * [new tag]         v1.0.0     -> v1.0.0
 * [new tag]         v1.1.0     -> v1.1.0
 * [new tag]         v1.1.1     -> v1.1.1
 * [new tag]         v1.1.2     -> v1.1.2
 * [new tag]         v1.2.0     -> v1.2.0
 * [new tag]         v1.2.1     -> v1.2.1
 * [new tag]         v1.2.2     -> v1.2.2
 * [new tag]         v1.2.3     -> v1.2.3
 * [new tag]         v1.3.0     -> v1.3.0
 * [new tag]         v1.3.1     -> v1.3.1
Fetching submodule external/egui at commit f83bf5e
fatal: remote error: upload-pack: not our ref 457c951951c19193afde16d1a4ac3c17a70518be
Errors during submodule fetch:
	external/egui
```

I am not that interest but if the binary is not working in Arm M1, may have to go this path one day.

**Comment by hinto-janai** [comment]
I cannot reproduce the error on macOS ARM, can you launch Gupax from the command-line and post the output? 

Also for git, you may need to use
```bash
git clone --recursive https://github.com/hinto-janai/gupax
```

**Comment by sonalder-darlene** [comment]
I have the same issue with M1 Max, I might take the time to build it but this isn't ideal as Gupax aimed to be an easy solution ^^

**Comment by gxanine** [comment]
This issue is related to Apple's security features. 

Apps downloaded from the Internet may be flagged as 'unsafe' if they lack proper notarization by Apple, a process that requires an active Apple Developer Program membership.

Source:
https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution
https://developer.apple.com/library/archive/releasenotes/Carbon/RN-LaunchServices/index.html

---

As a workaround you can remove the quarantine flag on the .app file by running the following command in your terminal:
```
xattr -d com.apple.quarantine /Applications/Gupax.app
```
(Replace `/Applications/Gupax.app` with your location of `Gupax.app`)

**Comment by hinto-janai** [comment]
Thanks for the info.

IIRC, the Apple Developer Program requires real world identification and a fee?
