### ISSUE TITLE
XMRig Uptime flickering beetwen 0s and actual time

### ISSUE THREAD

**Issue by Tomoyukiryu** [hinto-janai/gupax#52]
**Describe the bug**
What is the bug?
Edit: It happens on Processes tab of Status
**To Reproduce**
1.Start Gupax
2.Start P2Pool
3.Start XMRig
4.Go to Status Screen

**Screenshots**
If possible, add screenshots to help explain the bug.
I could add video, but I'm not sure if it would be of use

**OS & Version:**
Arch Linux, kernel version: 6.4.12-arch1-1, Gupax v1.3.1

**Comment by hinto-janai** [comment]
Is XMRig itself stable?

A video would help.
