### ISSUE TITLE
overlapping ui element

### ISSUE THREAD

**Issue by Nekothegamer** [hinto-janai/gupax#53]
**Describe the bug**
on the p2pool tab [the link telling you about monero nodes](https://github.com/hinto-janai/gupax#running-a-local-monero-node) overlaps on top of the bottom bar of the p2pool tab and blocks its usage

**To Reproduce**
1. Go to p2pool tab
2. See glitchy ui 

**Screenshots**
![Gupax_TF4TuXTcDf](https://github.com/hinto-janai/gupax/assets/112352776/aa8193bf-43ce-41dd-b9c7-725b10c01af1) 

**OS & Version:**
Windows 10, Gupax v1.3.1

**Comment by hinto-janai** [comment]
What is your screen resolution?

Can you try expanding the lower part of window downwards?

**Comment by hinto-janai** [comment]
Can you try [v1.3.2](https://github.com/hinto-janai/gupax/releases/tag/v1.3.2)?

There's a new pixel scaling option you can lower.

**Comment by Nekothegamer** [comment]
it works, the issue got fixed, thanks
