### ISSUE TITLE
Update GUPAX to current versions of packaged software

### ISSUE THREAD

**Issue by dukethorion** [hinto-janai/gupax#54]
Update Gupax to include the latest underlying packages:

[P2Pool v3.7](https://github.com/SChernykh/p2pool/releases/tag/v3.7)

[Monero v0.18.3.1](https://github.com/monero-project/monero/releases/tag/v0.18.3.1)

Latest version of XMRig.

**Comment by hinto-janai** [comment]
https://github.com/hinto-janai/gupax/releases/tag/v1.3.2
