### ISSUE TITLE
P2Pool fails to start

### ISSUE THREAD

**Issue by degesz** [hinto-janai/gupax#56]
P2Pool fails to start, the logs say:

`2023-10-19 20:40:11.9268 ZMQReader failed to connect to tcp://37.120.165.105:18083
P2Pool can't continue execution: panic at /home/runner/work/p2pool/p2pool/src/p2pool.cpp:802
2023-10-19 20:40:11.9273 P2Pool Couldn't start ZMQ reader: exception Operation cannot be accomplished in current state
2023-10-19 20:40:11.9273 Log stopped`

I think this is some network issue, anyone konws what is causing this?

**To Reproduce**
1. Go to 'P2Pool tab'
2. add remote node (lower saxony - DE)
3. click start P2Pool

**OS & Version:**
Linux Kubuntu, Gupax v1.3.1

**Comment by hinto-janai** [comment]
Your remote node must have [ZMQ](https://github.com/SChernykh/p2pool#gnulinux) enabled.
