### ISSUE TITLE
gupax compatibility issues

### ISSUE THREAD

**Issue by shaobo1** [hinto-janai/gupax#58]
I encountered some garbled characters in the Chinese version of Windows 10 Professional.

Env: Windows 10 专业版 22H2
       gupax version: v1.3.2
       Monitor resolution: 2560x1440

1.As I show in the picture below, garbled characters appear at position 1 in the picture.
2.Can you add some other colors to the second miner line? , similar to that in XMRig. eg: green.
3.In the position 3, the input box will be partially blocked. I tried to zoom in a little bit, but it was still a little blocked,I think there is a little compatibility issue。
image info:
![gupax](https://github.com/hinto-janai/gupax/assets/43359804/03f4ef77-dd1e-450b-af23-d2d5be22b9dd)

**Comment by hinto-janai** [comment]
Thanks for the report.

1. This is a known bug https://github.com/hinto-janai/gupax/issues/34 with no fix, it shouldn't cause any issues though, you can ignore the characters
2. Color is very hard to add back
3. https://github.com/hinto-janai/gupax/pull/60 should fix this in the next release
