### ISSUE TITLE
Gupax can use nodes which don't exist

### ISSUE THREAD

**Issue by SChernykh** [hinto-janai/gupax#62]
## OS & Version:
All OS

## Bug
Gupax can select xmr.theuplink.net which doesn't exist anymore. It even shows ping time for xmr.theuplink.net, but it's probably pinging some other node.

![u70hu9ak732c1](https://github.com/hinto-janai/gupax/assets/15806605/321cc190-3720-4364-9f56-483ad3ca5d04)

**Comment by shaobo1** [comment]
I've been encountering the same issue since last night.

**Comment by hinto-janai** [comment]
https://github.com/hinto-janai/gupax/pull/63 should fix. Waiting on next P2Pool before release.

**Comment by SChernykh** [comment]
@hinto-janai P2Pool v3.9 has been released.
