### ISSUE TITLE
Only 2 or 3 letter top-level domains are permitted in XMRig IP section.

### ISSUE THREAD

**Issue by soupslurpr** [hinto-janai/gupax#66]
## OS & Version:
Windows 11, Gupax v1.3.3

## Bug
Only 2 or 3 letter top-level domains are permitted in XMRig IP section. Can be seen at the end of the regex here:
https://github.com/hinto-janai/gupax/blob/1bfd72a8c2a1fe0a1583933e4d94a0450d0d964c/src/regex.rs#L45C200-L45C205

## Steps
1. Go to the XMRig section.
2. Click on IP and type a domain that uses a top-level domain that is not 2 or 3 letters.
3. See that it is not permitted when it should be.

**Comment by soupslurpr** [comment]
Try example.example.comm and it will fail

**Comment by hinto-janai** [comment]
Subdomains with long TLDs fail - thanks for the report, should be fixed next release.
