### ISSUE TITLE
Gupax not opening and just shows a white screen with unending loading 

### ISSUE THREAD

**Issue by monsiu** [hinto-janai/gupax#68]
## OS & Version:
e.g: Windows 11, Gupax v1.3.3

Windows 10 pro, Gupax v 1.1.2- v1.3.3
Thinkpad t540p, i5 4200M(4th gen cpu), intel graphics 4600

## Bug
What is the bug?
I can not open Gupax and all i get is a white screen followed by app closing and perpetual loading as seen by my cursor icon spinning and stopping. Nothing happens though. Gupax 1.1.1 works perfectly and anything beyond just shows that error of a white screen and loading. 

## Steps
1. Go to 'gupax folder'
2. Click on 'gupax executable'
3. See white screen followed by app closing itself

## Screenshots
If possible, add screenshots to help explain the bug.
![Screenshot (7)](https://github.com/hinto-janai/gupax/assets/69597591/9950c25b-883c-4f8d-8d50-5c7f99644cd9)

i see the white screen in the screenshot after just trying to open the executable.

![Screenshot (9)](https://github.com/hinto-janai/gupax/assets/69597591/bfcb5a74-d338-4ee4-907b-5ac87292b31d)

when trying to open it shows the whitescreen and this top most file pops in the folder but nothing happens and my cursor shows something is loading but nothing ever happens.

![cpu percent](https://github.com/hinto-janai/gupax/assets/69597591/f883c8ec-0de7-4e48-b274-662021b9df1a)

the screenshot after restarting my usages drop to normal.

##More info

## Crash report
If Gupax is crashing, you may have a file here:

- Windows: `C:\Users\YOUR_USER_NAME\AppData\Roaming\Gupax\crash.txt`
- macOS: `/Users/YOUR_USER_NAME/Library/Application Support/Gupax/crash.txt`
- Linux: `/home/YOUR_USER_NAME/.local/share/gupax/crash.txt`

If you do, please upload or copy-paste `crash.txt` here:
```
PanicInfo {
    payload: Any { .. },
    message: Some(
        wgpu error: Out of Memory
        ,
    ),
    location: Location {
        file: "C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\wgpu-0.13.1\\src\\backend\\direct.rs",
        line: 2391,
        col: 5,
    },
    can_unwind: true,
}

info:
   OS      | Windows
   args    | ArgsOs { inner: ["C:\\Users\\Martin\\Downloads\\Compressed\\gupax-v1.3.3-windows-x64-bundle\\gupax-v1.3.3-windows-x64-bundle\\Gupax.exe"] }
   commit  | 1bfd72a8c2a1fe0a1583933e4d94a0450d0d964c
   gupax   | v1.3.3
   p2pool  | v3.9 (bundled)
   xmrig   | v6.21.0 (bundled)
   uptime  | 3.2179003 seconds

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: CallWindowProcW
  17: DispatchMessageW
  18: SendMessageTimeoutW
  19: KiUserCallbackDispatcher
  20: NtUserDispatchMessage
  21: DispatchMessageW
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: BaseThreadInitThunk
  27: RtlUserThreadStart

```
##Info on error
This is the first error file i got in the dir and for some reason my 16gb ram was idling at 15.0gb out of 16gb. I have no clue why this happened as i even uninstalled monero gui and xmrig and rebooted. I think its maybe coz i was testing each version of gupax to see what ran on my device? i'm not sure but i thought i would just share.

After stabilizing and trying to open up Gupax it shots up but nothing is happening

No error file pops up after i clear the error file and try to replicate it. I believe its coz my memory drops to normal. 

I have another laptop i want to try it on and see if its the same. I'll keep you posted! Otherwise feel free to hmu on any clarrifications or info.

**Comment by monsiu** [comment]
Update: Tested gupax bundle on my lenovo yoga 510-14isk with an i3 6006U 8gb ddr4 ram with windows 11 and it works flawlessly. I think maybe its an optimization problem for older gen laptops?  

Even after reboot on my thinkpad I still get the same issue.

**Comment by hinto-janai** [comment]
Gupax has had problems with integrated CPU graphics in the past, this may be that again.

Does the Lenovo laptop have a dedicated GPU?

**Comment by monsiu** [comment]
hello both devices have intel HD Graphics no dedicated gpu at all on thinkpad and lenovo yoga
(hd graphics 4600 on thinkpad....the device that is crashing)

**Comment by hinto-janai** [comment]
[`v1.1.2`](https://github.com/hinto-janai/gupax/commit/c592f0c9af8c2871dd7adcb9d87303dcff6c23b9) changed Gupax's GUI backend on Windows - this was done because the previous one was crashing like this on some machines, although seems like this one crashes too...

I don't have a machine that crashes Gupax, are you willing to test some binaries?

**Comment by monsiu** [comment]
> [`v1.1.2`](https://github.com/hinto-janai/gupax/commit/c592f0c9af8c2871dd7adcb9d87303dcff6c23b9) changed Gupax's GUI backend on Windows

We have our culprit then...since the code from that change carries on, then nothing beyond 1.1.1 works.


> I don't have a machine that crashes Gupax, are you willing to test some binaries?

Sure. I am ok with that. Whenever you're ready drop them.

**Comment by hinto-janai** [comment]
Here are some binaries that reverts back to the old GUI backend: https://github.com/hinto-janai/gupax/actions/runs/7322459490

Windows one is here: https://github.com/hinto-janai/gupax/actions/runs/7322459490/artifacts/1134248644

Could you test to see if it works on both machines?

**Comment by monsiu** [comment]
Hello @hinto-janai i have tested the windows binary and it works beautifully with the Lenovo t540p thinkpad(the one with the problem) as well as the Lenovo yoga 510-14isk both machines on windows 10.

Good stuff!

**Comment by hinto-janai** [comment]
Could you try this on both machines as well? https://github.com/hinto-janai/gupax/actions/runs/7364404804

Windows: https://github.com/hinto-janai/gupax/actions/runs/7364404804/artifacts/1140320631

**Comment by monsiu** [comment]
Hey it's been a while...yes I have tested them and they work without the issue.

This is wonderful.

**Comment by monsiu** [comment]
Wait wait wait....my threads dropped to 4 when i am supposed to have 8. 
Here is the Gupax 1.1 which shows i can utilize 8 full threads but in the binary you shared i can only see 4...

Is it for like test version and you limited to 4 or is this another issue. I have a i7 4900MQ. Here is a screenshot of both gupax versions and you can see the 1.1(the former only version that worked before the one you shared).

![Screenshot (16)](https://github.com/hinto-janai/gupax/assets/69597591/06b5ed2a-fb6f-4476-bb63-184dd724f216)

**Comment by hinto-janai** [comment]
In the `Status` -> `Benchmarks` tab, can you show what CPU Gupax detects?

**Comment by monsiu** [comment]
It detects the i7 4900MQ (Quad core 8 Threads) also without Gupax i can mine on all 8 threads with xmrig.

![Capture](https://github.com/hinto-janai/gupax/assets/69597591/7567346e-9fbb-4123-89cb-83774fd01c6b)

**Comment by hinto-janai** [comment]
Interesting, the other threads may be efficiency/burst cores and not necessarily good for sustained mining - the API that fetches CPU count in Gupax will fallback to "sustain" cores in this instance. 

All the benchmarks at https://xmrig.com/benchmark?cpu=Intel%28R%29+Core%28TM%29+i7-4900MQ+CPU+%40+2.80GHz are submitted only using 4 threads as well, can you test the difference in hashrate using 4 vs 8 threads?

**Comment by monsiu** [comment]
Hashrate on 8 threads was 600-700h/s but when i turn off multi-threading i get 1900h/s-2000h/s

**Comment by monsiu** [comment]
Sorry i closed by mistake

**Comment by hinto-janai** [comment]
What do you mean by 'turn off multi-threading'? 8 threads was 600-700h/s, 4 threads was 1700-2000h/s?

**Comment by monsiu** [comment]
oops sorry I meant hyper-threading...here is its definition from bios.

![2024-02-25-16-21-57-899.jpg](https://github.com/hinto-janai/gupax/assets/69597591/f4be99b3-f525-46be-8f99-49379415da69)

now with hyperthreading enabled from bios...this is what I see as my cores and processors (aka threads)

![2024-02-25-16-12-54-869.jpg](https://github.com/hinto-janai/gupax/assets/69597591/8d4c2073-0f37-4999-98d6-ed3c80cdb0b6)


now if I disable multi threading (which most miners suggest boosts speeds and hashes) as u see I now have 4 threads from the previous 8 but mining hashes are beautifully fast.

![2024-02-25-16-26-20-798.jpg](https://github.com/hinto-janai/gupax/assets/69597591/394cff52-8403-46ef-b0c9-7031cac701b2)

Sorry if I'm not clear but it's the best way I can explain. anyway that's why In the benchmarks you see people use 4 threads in mining and not 8... so when I use 4 threads too(by turning off hyper threading) I get close to match those hashes. In reality we(i7 4900mq guys) can use 8 but to get top speeds they turned off hyper threading.

I kept mixing multi threading and hyper threading sorry😅
