### ISSUE TITLE
Gupax fails to start with message being "wgpu error: Out of Memory"

### ISSUE THREAD

**Issue by carrothn** [hinto-janai/gupax#69]
## OS & Version:
Windows IoT Enterprise LTSC 2021, Gupax 1.3.3

## Bug
Gupax not starting with error message being "wgpu error: Out of Memory"

## Steps
1. Open Gupax.exe

## Crash report
[crash.txt](https://github.com/hinto-janai/gupax/files/13710176/crash.txt)

**Comment by hinto-janai** [comment]
> Windows IoT Enterprise LTSC 2021

This is most likely the problem.

Can you try seeing if [`v1.1.1`](https://github.com/hinto-janai/gupax/releases/tag/v1.1.1) works?

**Comment by hinto-janai** [comment]
I don't have a machine with that Windows, are you willing to test some binaries?

**Comment by hinto-janai** [comment]
Please follow https://github.com/hinto-janai/gupax/issues/68#issuecomment-1869021095

**Comment by hinto-janai** [comment]
Could you try this as well? https://github.com/hinto-janai/gupax/issues/68#issuecomment-1872532673
