### ISSUE TITLE
Mine to a pool

### ISSUE THREAD

**Issue by gtxg16** [hinto-janai/gupax#70]
**Feature request**
Be able to mine to a pool

Listen, I know p2pool is better and everything. I agree with that. But is there really no way to mine to a pool? Again, I am aware that p2pool is better. But i cannot find another GUI for XMRIG mining

**Comment by hinto-janai** [comment]
You can specify XMRig to mine to any pool you want: https://github.com/hinto-janai/gupax#XMRig-1
