### ISSUE TITLE
Stuck on Fetching Package Metadata at 10%

### ISSUE THREAD

**Issue by Iempire786** [hinto-janai/gupax#73]
## OS & Version: Windows 11, Gupax v1.3.3
e.g: Windows 11, Gupax v1.3.3

## Bug
What is the bug?
Stuck on Fetching Package Metadata at 10%

## Steps
1. Go to '.just start the app and then it remains stuck on 10%"

## Screenshots
If possible, add screenshots to help explain the bug.
![image](https://github.com/hinto-janai/gupax/assets/154922524/d6556c43-501d-4648-ba3f-b61a383ed0ed)
![Screenshot 2023-12-27 030134](https://github.com/hinto-janai/gupax/assets/154922524/0d4383d2-ea15-4659-a2fd-7b8f9a27cb1f)

## Crash report
If Gupax is crashing, you may have a file here:

- Windows: `C:\Users\YOUR_USER_NAME\AppData\Roaming\Gupax\crash.txt`
- macOS: `/Users/YOUR_USER_NAME/Library/Application Support/Gupax/crash.txt`
- Linux: `/home/YOUR_USER_NAME/.local/share/gupax/crash.txt`

If you do, please upload or copy-paste `crash.txt` here:
```
paste inside here.
```

**Comment by hinto-janai** [comment]
1. Do you have an internet connection?
2. Can you turn off `Update via Tor` and try again?

**Comment by Iempire786** [comment]
surprisingly the problem solved itself and it download but now I am facing the same problem on another PC. 

I will try turning off update via Tor. 

Thank you and have a nice day!
