### ISSUE TITLE
Gupax won't launch

### ISSUE THREAD

**Issue by kurpav00** [hinto-janai/gupax#78]
## OS & Version:
Windows 10 Home, Gupax v1.3.5

## Bug
When I try running Gupax.exe, nothing happens. It does not matter if I try launching it by double clicking or in a command prompt. In command prompt, the program simply terminates after a few seconds returning the %errorlevel% 0, but no GUI is opened.

## Steps
1. Go to the downloaded and unpacked Gupax folder (added among the virus protection exceptions)
2. Double click Gupax.exe (or run Gupax.exe from command prompt)
3. See nothing happening, no errors, no messages, nothing

## Screenshots
![Capture](https://github.com/hinto-janai/gupax/assets/67642253/e478ddf5-714a-465e-af52-dbde879b63a4)
no GUI opened
## Crash report
No crash.txt file is generated.

**Comment by kurpav00** [comment]
Intel Celeron B830 CPU @ 1.80GHz
Intel HD Graphics

**Comment by hinto-janai** [comment]
Can you see if using [`v1.3.3`](https://github.com/hinto-janai/gupax/releases/tag/v1.3.3) works?

**Comment by kurpav00** [comment]
Yes, v1.3.3 works. V1.3.4 and 1.3.5 don't. Thank you.

**Comment by Cyrix126** [comment]
@kurpav00 

Hello can you try my [fork](https://github.com/Cyrix126/gupaxx/releases) ? specially for windows it is using a different backend  for rendering (glow instead of wgpu) and it's using more up to date deps. Let me know if it works for you.

**Comment by kurpav00** [comment]
@Cyrix126 I tried both the version 1.0.0 and 0.1.10, but none of them works, demonstrating the same behavior - the program does not launch at all, returning the exit status 0.

**Comment by Cyrix126** [comment]
@kurpav00 ,
Would you like to try to help me debug your issue ? we can talk over matrix or session, whichever you prefer. I will give you a build that will create a log file at runtime. That should help knowing what's going on.

**Comment by Cyrix126** [comment]
After having the log file, here is the relevant part.

```
DEBUG [eframe] Using the glow renderer
DEBUG [eframe::native::glow_integration] Event::Resumed
DEBUG [eframe::native::glow_integration] trying to create glutin Display with config: ConfigTemplateBuilder { template: ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: ConfigSurfaceTypes(WINDOW), api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None } }
DEBUG [eframe::native::glow_integration] using the first config from config picker closure. config: Wgl(Config { inner: Config { hdc: 1057034209, pixel_format_index: 2 } })
DEBUG [eframe::native::glow_integration] successfully created GL Display with version: WGL and supported features: DisplayFeatures(FLOAT_PIXEL_FORMAT | SWAP_CONTROL | MULTISAMPLING_PIXEL_FORMATS | SRGB_FRAMEBUFFERS)
DEBUG [eframe::native::glow_integration] creating gl context using raw window handle: Some(Win32(Win32WindowHandle { hwnd: 0xe073a, hinstance: 0x7ff77dca0000 }))
WARN [eframe::native::glow_integration] Failed to create context using default context attributes ContextAttributes { release_behavior: Flush, debug: false, robustness: NotRobust, profile: None, api: None, shared_context: None, raw_window_handle: Some(Win32(Win32WindowHandle { hwnd: 0xe073a, hinstance: 0x7ff77dca0000 })) } due to error: [ffffffffc0072095] OS Error -1073274731 (FormatMessageW() returned error 317) (os error -1073274731)
DEBUG [eframe::native::glow_integration] Retrying with fallback context attributes: ContextAttributes { release_behavior: Flush, debug: false, robustness: NotRobust, profile: None, api: Some(Gles(None)), shared_context: None, raw_window_handle: Some(Win32(Win32WindowHandle { hwnd: 0xe073a, hinstance: 0x7ff77dca0000 })) }
ERROR [eframe::native::run] Exiting because of error: glutin error: extension to create ES context with wgl is not present during event Resumed
DEBUG [eframe::native::run] Asking to exit event loop…
DEBUG [eframe::native::run] Received Event::LoopExiting - saving app state…
DEBUG [eframe::native::run] eframe window closed
```

**Comment by Cyrix126** [comment]
It seems that the cpu is limited to OpenGL 3.1. Maybe glow/glutin is trying to create a context with a newer version. I'll investigate this further.

**Comment by Cyrix126** [comment]
using wgpu instead of glow output this warning:
```
WARN [wgpu_hal::gles::adapter] Returned GL context is 3.1, when 3.3+ is needed
```

**Comment by hinto-janai** [comment]
@Cyrix126 thanks for investigating this, does this mean CPUs pre-2010 are not supported? Is there a simple fix or is there a tradeoff in supporting OpenGL <3.3?

**Comment by Cyrix126** [comment]
@hinto-janai you can see a simple fix here https://github.com/Cyrix126/gupaxx/commit/bf741316185d07637370d4be6889f72d5d1c3a96
You need to bring wgpu dependence with the same version that eframe use and enable the angle feature.
See the issue I mentioned if you want to know the details.
