### ISSUE TITLE
gupax crashes immediatley

### ISSUE THREAD

**Issue by Tomoyukiryu** [hinto-janai/gupax#84]
## OS & Version:
ArchLinux, kernel: 6.6.21-1-lts

## Bug
gupax won't start when clicked in visual file manager, in my case it's dolphin from kde plasma 6.0. When I try to launch it thru terminal it crashes immediately . 

## Steps
in visual file manager:
1.click binary
2.nothing happens
in terminal:
1.start gupax binary
2. crashes with error

## Crash report
PanicInfo {
    payload: Any { .. },
    message: Some(
        called `Option::unwrap()` on a `None` value,
    ),
    location: Location {
        file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glutin-0.30.10/src/api/egl/surface.rs",
        line: 239,
        col: 44,
    },
    can_unwind: true,
    force_no_backtrace: false,
}

info:
   OS      | Linux
   args    | ArgsOs { inner: ["/mnt/nvme1n1p1/gupax-v1.3.5-linux-x64-bundle/gupax", "--no-startup"] }
   commit  | 22f11ce7d8d1f550fa53a28e9efb74424a56c46b
   gupax   | v1.3.5
   p2pool  | v3.10 (bundled)
   xmrig   | v6.21.0 (bundled)
   uptime  | 0.28010976 seconds

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: __libc_start_main
  18: <unknown>

**Comment by hinto-janai** [comment]
Are you using integrated CPU graphics (no GPU?)

Can you try seeing if https://github.com/hinto-janai/gupax/releases/tag/v1.3.3 works?

**Comment by Tomoyukiryu** [comment]
im using discrete graphics,  and 1.3.3 same crash massage. the only diffrence beetwen it worked and not working is that when kde plasma updated to 6.0 it switched to wayland

**Comment by Tomoyukiryu** [comment]
I noticed that, optimus-manager is not working and everything is on integrated. it seems its not an issue with gupax, but i will not close this issue until im  sure its the source of guipax crashes. Agreed?

**Comment by Tomoyukiryu** [comment]
I fixed the problem with discrete nvidia gpu. Still the same crash log for gupax. All applications now open on discrete gpu

**Comment by Dannyjelll** [comment]
I am having the same issue on discrete AMD gpu

**Comment by Dannyjelll** [comment]
Also Arch Linux

**Comment by Dannyjelll** [comment]
Tried building different releases myself again to no avail, still same error

**Comment by hinto-janai** [comment]
Does the latest release work? https://github.com/hinto-janai/gupax/releases/tag/v1.3.6

**Comment by Dannyjelll** [comment]
Yes it does, thank you!

**Comment by Tomoyukiryu** [comment]
1.3.6 starts, but when I try to click text field for password it stops responding and I need to manually kill  the process. Unfortunately it doesn't crash so the crash.txt doesn't have anything in it.

**Comment by Dannyjelll** [comment]
I cant reproduce that, works for me on arch with dedicated gpu and on my server that only has an AMD cpu.

**Comment by Tomoyukiryu** [comment]
Update of something fixed it.
