### ISSUE TITLE
No XMR showing

### ISSUE THREAD

**Issue by STUKguy** [hinto-janai/gupax#88]
Morning All,

Not sure if this is an issue or if im doing something wrong but i have been running Gupax for 3 days now and my XMR balance is still 0? i have checked my wallet which also says 0.

![image](https://github.com/hinto-janai/gupax/assets/66088795/a8c5c0e6-2289-4e74-ba59-a9c94ede7ebe)

**Comment by itaymigdal** [comment]
@STUKguy  Having the same issue here, what was your resolution?

**Comment by STUKguy** [comment]
> @STUKguy Having the same issue here, what was your resolution?

Hey, it eventually showed up after 7 days of mining.

**Comment by itaymigdal** [comment]
Thanks!
