### ISSUE TITLE
Intro vid blank

### ISSUE THREAD

**Issue by Hueristic** [hinto-janai/gupax#90]
https://private-user-images.githubusercontent.com/101352116/207978455-6ffdc0cc-204c-4594-9a2f-e10c505745bc.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzOTU1OTQsIm5iZiI6MTcxMzM5NTI5NCwicGF0aCI6Ii8xMDEzNTIxMTYvMjA3OTc4NDU1LTZmZmRjMGNjLTIwNGMtNDU5NC05YTJmLWUxMGM1MDU3NDViYy5tcDQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QyMzA4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTNlMGRlODVmMTk1N2JiYWU3NDhmNTNkNWQ5NjFlZjgzODc3MTUzOTViYjk3ODgxMzM4NDZmMjBjMjQwZjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mdu3bfx4UQU24Xt8bJar7Ats93AJoAjT7__kyMmUNfQ

**Comment by hinto-janai** [comment]
The video is not blank.
