### ISSUE TITLE
Program is a complete nightmare!  Try displaying the OS requirements somewhere!

### ISSUE THREAD

**Issue by Hueristic** [hinto-janai/gupax#91]
Literally wasted hours on this pos with ZERO ERRORS only shutdown on startup because Win 7 does not support  conpty!

TRY writing a damn check for os and displaying a error or something if your not going to bother to put the Os requirements prominently displayed.

Everyone is not an M$ sheep that downgrades when ordered to.

**Comment by HardenedSteel** [comment]
Did you try opening with command line? 

Also Windows 7 is very outdated and deprecated years ago however I agree Gupax should state system requirements.

**Comment by hinto-janai** [comment]
Windows 7 was deprecated [4 years ago](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962).

Consider either upgrading or using a different OS.

> Gupax should state system requirements.

Will add them, thanks.
