### ISSUE TITLE
Gupax won't start on Ubuntu 24.04/RPi5

### ISSUE THREAD

**Issue by ubuntophe** [hinto-janai/gupax#92]
## OS & Version: 
Ubuntu 24.04 on a RPi5
I tried Gupax v1.3.3 & v1.3.6

## Bug
Clicking on Gupax or Gupax.AppImage will not launch Gupax

## Steps
I followed the Build instructions (install Rust, Cargo...) no error messages.

**Comment by ubuntophe** [comment]
Input:
```
sudo chmod +x gupax-v1.3.6-linux-x64-bundle/gupax
sudo ./gupax-v1.3.6-linux-x64-bundle/gupax
```
Result: 
`./gupax-v1.3.6-linux-x64-bundle/gupax: 1: Syntax error: "(" unexpected`

**Comment by hinto-janai** [comment]
Can you try:
```bash
cd gupax-v1.3.6-linux-x64-bundle/
./gupax
```

**Comment by ubuntophe** [comment]
result: 
`bash: ./gupax: cannot execute binary file: Exec format error`

**Comment by hinto-janai** [comment]
Ah, it is because Raspberry Pi's have ARM CPUs, not x86.

P2Pool has Linux ARM binaries but XMRig/Gupax doesn't.

[You can try building XMRig for ARM](https://xmrig.com/docs/miner/build). I recommend skipping Gupax since it'll take up a lot of CPU on a machine like a RPi5.

**Comment by ubuntophe** [comment]
Thanks for your quick reply. It is a RPi5 dedicated only to that so I thought it would be enough CPU.
