### ISSUE TITLE
Adding config file to Xmrig

### ISSUE THREAD

**Issue by hassan0ibrahim** [hinto-janai/gupax#97]
**Feature request**
Adding config file to Xmrig
I tried to put a config.json in the Xmrig directory inside gupax folder but it wasn't used

**Comment by hinto-janai** [comment]
You'll need to use [overriding command line arguments](https://github.com/hinto-janai/gupax?tab=readme-ov-file#XMRig-1) and specify `--config=/file/path/` if you want to use a custom `config.json`.
