### ISSUE TITLE
generate command line arguments

### ISSUE THREAD

**Issue by SunilPaul174** [hinto-janai/gupax#98]
**Feature request**
Add an option to the xmrig tab to show what commandline arguments are being passed to xmrig

It would be really helpful for newcomers when learning to use the program but wanting to use a config file. The ports and url options can be a little confusing if attempting to use the overriding command line arguments

**Comment by hinto-janai** [comment]
This is not in the GUI but the passed command line arguments can be seen from log output: https://github.com/hinto-janai/gupax?tab=readme-ov-file#Logs.

**Comment by SunilPaul174** [comment]
Oh that's good, I was looking through htop 😅. Should i close this issue?
